import type { CardDef } from '@adulting/shared';

/** Steward: attrition. Block is the resource, not just the defence. */
export const stewardCards: readonly CardDef[] = [
  {
    id: 'stw_tidy',
    name: 'Tidy',
    classId: 'steward',
    type: 'attack',
    rarity: 'common',
    cost: 1,
    needsTarget: true,
    exhaust: false,
    effects: [{ kind: 'damage', amount: 6, target: 'chosenFoe' }],
    text: 'Deal 6 damage.',
  },
  {
    id: 'stw_brace',
    name: 'Brace',
    classId: 'steward',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    needsTarget: false,
    exhaust: false,
    effects: [{ kind: 'block', amount: 6, target: 'self' }],
    text: 'Gain 6 Block.',
  },
  {
    id: 'stw_threshold',
    name: 'Hold the Threshold',
    classId: 'steward',
    type: 'skill',
    rarity: 'uncommon',
    cost: 2,
    needsTarget: false,
    exhaust: false,
    effects: [
      { kind: 'block', amount: 10, target: 'self' },
      { kind: 'status', status: 'bulwark', stacks: 1, target: 'self' },
    ],
    text: 'Gain 10 Block. Bulwark: keep half your Block next turn.',
    loreRef: 'lore.ch1.threshold',
  },
  {
    id: 'stw_sweep',
    name: 'Long Sweep',
    classId: 'steward',
    type: 'attack',
    rarity: 'uncommon',
    cost: 2,
    needsTarget: false,
    exhaust: false,
    effects: [{ kind: 'damage', amount: 5, target: 'allFoes' }],
    text: 'Deal 5 damage to all foes.',
  },
  {
    id: 'stw_bulwark_break',
    name: 'Bulwark Break',
    classId: 'steward',
    type: 'attack',
    rarity: 'rare',
    cost: 2,
    needsTarget: true,
    exhaust: false,
    effects: [{ kind: 'blockAsDamage', ratio: 1, target: 'chosenFoe' }],
    text: 'Deal damage equal to your Block.',
  },
  {
    id: 'stw_shelter',
    name: 'Shelter',
    classId: 'steward',
    type: 'skill',
    rarity: 'rare',
    cost: 2,
    needsTarget: false,
    exhaust: true,
    effects: [{ kind: 'block', amount: 8, target: 'allAllies' }],
    text: 'All allies gain 8 Block. Exhaust.',
  },
];
