import type { CardDef } from '@adulting/shared';

/** Warden: only fully expressed in coop. Solo decks get the weaker half. */
export const wardenCards: readonly CardDef[] = [
  {
    id: 'wrd_mend',
    name: 'Mend',
    classId: 'warden',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    needsTarget: true,
    exhaust: false,
    effects: [{ kind: 'heal', amount: 6, target: 'chosenAlly' }],
    text: 'Heal an ally for 6.',
  },
  {
    id: 'wrd_ward',
    name: 'Ward',
    classId: 'warden',
    type: 'skill',
    rarity: 'common',
    cost: 1,
    needsTarget: true,
    exhaust: false,
    effects: [{ kind: 'block', amount: 7, target: 'chosenAlly' }],
    text: 'An ally gains 7 Block.',
  },
  {
    id: 'wrd_secondwind',
    name: 'Second Wind',
    classId: 'warden',
    type: 'skill',
    rarity: 'uncommon',
    cost: 1,
    needsTarget: true,
    exhaust: true,
    effects: [{ kind: 'energy', amount: 1, target: 'chosenAlly' }],
    text: 'An ally gains 1 Energy. Exhaust.',
  },
  {
    id: 'wrd_vigil',
    name: 'Vigil',
    classId: 'warden',
    type: 'power',
    rarity: 'rare',
    cost: 2,
    needsTarget: false,
    exhaust: true,
    effects: [{ kind: 'status', status: 'regen', stacks: 3, target: 'party' }],
    text: 'The whole party gains 3 Regen. Exhaust.',
    loreRef: 'lore.ch3.vigil',
  },
];
